scrape_configs:
  - job_name: kafka-app
    scrape_interval: 5s
    static_configs:
      - targets:
          - kafka-app:8082
  - job_name: pushgateway
    scrape_interval: 5s
    static_configs:
      - targets:
          - prometheus-pushgateway:9091