version = 1

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/emmanuelneri/go-study/examples/host-caller"]

  [analyzers.meta]
    import_paths = ["github.com/emmanuelneri/go-study/examples/rest-app"]
