// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	domain "app/pkg/domain"

	mock "github.com/stretchr/testify/mock"
)

// OrderRepository is an autogenerated mock type for the OrderRepository type
type OrderRepository struct {
	mock.Mock
}

// Save provides a mock function with given fields: order
func (_m *OrderRepository) Save(order *domain.Order) error {
	ret := _m.Called(order)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Order) error); ok {
		r0 = rf(order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
